export type LearningTrack = { currentItemId: string | null; completedItemIds: string[]; bookmarkedItemIds: string[]; lastReadAt: number | null; textSize: 'default' | 'large' | 'xlarge' }
export type LearningState = { version: 1; tracks: Record<string, LearningTrack>; notes: Record<string, string>; recentItemIds: string[]; quizzesCompleted: string[] }
import {preserveCorruptStorage} from './storageRecovery'

const KEY='noortools:phase3e:learning:v1'; const MAX_RECENT=20; const MAX_NOTES=200; const MAX_IDS=200
const blankTrack=():LearningTrack=>({currentItemId:null,completedItemIds:[],bookmarkedItemIds:[],lastReadAt:null,textSize:'default'})
export const blankLearningState=():LearningState=>({version:1,tracks:{},notes:{},recentItemIds:[],quizzesCompleted:[]})
const clean=(value:unknown,max:number):string=>typeof value==='string'?value.replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max):''
function validTrack(value:unknown):LearningTrack{if(!value||typeof value!=='object'||Array.isArray(value))return blankTrack();const v=value as Record<string,unknown>;const ids=(x:unknown)=>Array.isArray(x)?x.filter(y=>typeof y==='string').map(y=>clean(y,160)).filter(Boolean).slice(-MAX_IDS):[];return{currentItemId:typeof v.currentItemId==='string'&&v.currentItemId.trim()?clean(v.currentItemId,160):null,completedItemIds:ids(v.completedItemIds),bookmarkedItemIds:ids(v.bookmarkedItemIds),lastReadAt:typeof v.lastReadAt==='number'&&Number.isFinite(v.lastReadAt)&&v.lastReadAt>=0?v.lastReadAt:null,textSize:v.textSize==='large'||v.textSize==='xlarge'?v.textSize:'default'}}
function migrate(raw:unknown):LearningState{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Stored learning data has an invalid structure.');const v=raw as Record<string,unknown>;if(v.version!==1&&v.version!==undefined)throw new Error('Stored learning data uses an unsupported version.');const tracks:Record<string,LearningTrack>={};if(v.tracks&&typeof v.tracks==='object'&&!Array.isArray(v.tracks))for(const[k,val]of Object.entries(v.tracks).slice(0,50))tracks[clean(k,80)]=validTrack(val);const notes:Record<string,string>={};if(v.notes&&typeof v.notes==='object'&&!Array.isArray(v.notes))for(const[k,val]of Object.entries(v.notes).slice(0,MAX_NOTES)){const n=clean(val,5000);if(n)notes[clean(k,160)]=n}const recentItemIds=Array.isArray(v.recentItemIds)?v.recentItemIds.filter(x=>typeof x==='string').map(x=>clean(x,160)).filter(Boolean).slice(-MAX_RECENT):[];const quizzesCompleted=Array.isArray(v.quizzesCompleted)?v.quizzesCompleted.filter(x=>typeof x==='string').map(x=>clean(x,160)).filter(Boolean).slice(-MAX_RECENT):[];return{version:1,tracks,notes,recentItemIds,quizzesCompleted}}
export function loadLearningState():LearningState{try{const raw=localStorage.getItem(KEY);if(!raw)return blankLearningState();try{return migrate(JSON.parse(raw))}catch(error){preserveCorruptStorage(KEY,raw,error instanceof Error?error.message:'Stored learning data could not be migrated safely.')}}catch{}return blankLearningState()}
export function saveLearningState(state:LearningState){localStorage.setItem(KEY,JSON.stringify({...state,version:1}))}
export function resetLearningState(){localStorage.removeItem(KEY);localStorage.removeItem(`${KEY}:recovery:v1`);return blankLearningState()}
export function updateTrack(state:LearningState,module:string,patch:Partial<LearningTrack>):LearningState{const current=state.tracks[module]??blankTrack();return{...state,tracks:{...state.tracks,[module]:{...current,...patch}}}}
export function markRecent(state:LearningState,itemId:string):LearningState{const id=clean(itemId,160);return id?{...state,recentItemIds:[...state.recentItemIds.filter(x=>x!==id),id].slice(-MAX_RECENT)}:state}
export function toggleBookmark(state:LearningState,module:string,itemId:string):LearningState{const track=state.tracks[module]??blankTrack();const set=new Set(track.bookmarkedItemIds);if(set.has(itemId))set.delete(itemId);else set.add(itemId);return updateTrack(state,module,{bookmarkedItemIds:[...set].slice(-MAX_IDS)})}
export function markCompleted(state:LearningState,module:string,itemId:string):LearningState{const track=state.tracks[module]??blankTrack();return updateTrack(markRecent(state,itemId),module,{completedItemIds:[...new Set([...track.completedItemIds,itemId])].slice(-MAX_IDS),currentItemId:itemId,lastReadAt:Date.now()})}
export function setNote(state:LearningState,itemId:string,note:string):LearningState{const key=clean(itemId,160);const value=clean(note,5000);const notes={...state.notes};if(value)notes[key]=value;else delete notes[key];return{...state,notes}}
