import { describe, expect, it } from 'vitest'
import { dedupeMosques, distanceMeters, formatDistance, mapNominatimResults, mapOverpassResults, mosquePrayerState, sortByDistance, validCoordinate } from './mosque'
const mosque = (id: string, lat: number, lon: number, name = id) => ({ id, source: 'OpenStreetMap', sourceUrl: 'https://www.openstreetmap.org/node/1', lastUpdated: null, name, address: null, coordinates: { lat, lon }, phone: null, website: null, openingHours: null, facilities: [], jummah: [], mosqueTimetable: null, sourceTags: {} })
describe('Phase 3D mosque domain', () => {
  it('validates coordinate boundaries and calculates straight-line distance', () => { expect(validCoordinate({ lat: 19.076, lon: 72.8777 })).toBe(true); expect(validCoordinate({ lat: 91, lon: 0 })).toBe(false); expect(validCoordinate({ lat: 0, lon: 181 })).toBe(false); expect(distanceMeters({ lat: 0, lon: 0 }, { lat: 0, lon: 1 })).toBeGreaterThan(111000); expect(formatDistance(750)).toBe('750 m') })
  it('sorts nearest first and de-duplicates provider records', () => { const items = [mosque('far', 0, 2), mosque('near', 0, 1), mosque('near', 0, 1)]; const unique = dedupeMosques(items); expect(unique).toHaveLength(2); expect(sortByDistance(unique, { lat: 0, lon: 0 }).map(x => x.id)).toEqual(['near', 'far']) })
  it('maps only provider-supplied fields and keeps missing fields unavailable', () => { const data = { elements: [{ type: 'node', id: 123, lat: 19, lon: 72, timestamp: '2026-09-15T01:00:00Z', tags: { amenity: 'place_of_worship', religion: 'muslim', name: 'Masjid Test', phone: '+91 11111', website: 'https://example.com', 'addr:street': 'Example Road', wheelchair: 'yes', toilets: 'yes' } }] }; const [m] = mapOverpassResults(data); expect(m.name).toBe('Masjid Test'); expect(m.address).toBe('Example Road'); expect(m.facilities).toEqual(['Wheelchair access', 'Toilets']); expect(m.jummah).toEqual([]); expect(m.mosqueTimetable).toBeNull(); expect(m.phone).toBe('+91 11111'); expect(m.website).toBe('https://example.com/') })
  it('maps safe Nominatim choices and rejects malformed coordinate results', () => { expect(mapNominatimResults([{ lat: '19.1', lon: '72.8', display_name: 'Mumbai' }, { lat: 'bad', lon: 1, display_name: 'bad' }])).toHaveLength(1) })
  it('does not substitute NoorTools prayer calculations for mosque timetable', () => { const unavailable = mosquePrayerState(null, new Date('2026-09-15T06:00:00Z'), 'Asia/Kolkata'); expect(unavailable.states).toEqual({}); expect(unavailable.reason).toContain('Verified mosque timetable unavailable.') })
  it('derives mosque-specific state only from the supplied timetable timezone', () => { const now = new Date('2026-09-15T10:30:00Z'); const result = mosquePrayerState({ Dhuhr: '15:59', Asr: '16:01' }, now, 'Asia/Kolkata'); expect(result.states.Dhuhr).toBe('past'); expect(result.states.Asr).toBe('upcoming'); expect(result.reason).toContain('mosque-provided timetable') })
})
