import { useMemo, useState } from 'react'
import { MODULE_LABELS, SOURCE_RECORDS, audioStatus, canShare, moduleItems, searchLearning, sourceStatusLabel, type LearningItem, type LearningModule } from './learning'
import { loadLearningState, markCompleted, markRecent, saveLearningState, setNote, toggleBookmark, type LearningState } from './learningStorage'

const modules = Object.keys(MODULE_LABELS) as LearningModule[]

export default function Phase3ELauncher(){
 const [open,setOpen]=useState(false); const [module,setModule]=useState<LearningModule>('prophets'); const [state,setState]=useState<LearningState>(loadLearningState); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<LearningItem|null>(null)
 const [notesOnly,setNotesOnly]=useState(false)
 const items=useMemo(()=>{const base=query.trim()?searchLearning(query):moduleItems(module); return notesOnly?base.filter(item=>state.notes[item.id]):base},[query,module,notesOnly,state.notes])
 const commit=(next:LearningState)=>{setState(next);saveLearningState(next)}
 const openItem=(item:LearningItem)=>{setSelected(item);commit(markRecent(state,item.id))}
 if(!open)return <button className="phase3e-launcher primary" onClick={()=>setOpen(true)} aria-label="Open Seerah, Prophets and Islamic Learning">3E · Learning</button>
 return <div className="phase3e-overlay" role="dialog" aria-modal="true" aria-label="NoorTools Islamic history and learning"><div className="phase3e-panel" dir="auto">
  <header className="card-head"><div><p className="eyebrow">NOORTOOLS · PHASE 3E</p><h1>Stories, History & Learning</h1><p className="muted">Only verified, cleared source content can appear as SOURCE CONTENT.</p></div><button onClick={()=>{setOpen(false);setSelected(null)}} aria-label="Close learning">×</button></header>
  {!selected?<>
   <div className="phase3e-tabs" role="tablist" aria-label="Learning modules">{modules.map(value=><button key={value} className={module===value?'selected':''} role="tab" aria-selected={module===value} onClick={()=>{setModule(value);setQuery('');setNotesOnly(false)}}>{MODULE_LABELS[value]}</button>)}<button className={notesOnly?'selected':''} role="tab" aria-selected={notesOnly} onClick={()=>setNotesOnly(v=>!v)}>Bookmarks / Notes</button></div>
   <div className="search-box"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search verified learning content" aria-label="Search learning content" />{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Clear search">×</button>}</div>
   <section className="phase3e-grid" aria-live="polite">{items.length===0?<div className="phase3e-card phase3e-empty"><h2>No verified content available</h2><p className="muted">This module is ready, but NoorTools will not fabricate or rewrite religious/history content. Content appears here only after source, redistribution, provenance and review requirements are satisfied.</p><p className="footnote">No seeded progress · no generated stories · no invented quiz answers.</p></div>:items.map(item=><article className="phase3e-card" key={item.id}><div className="phase3e-meta"><span className="phase3e-pill">{MODULE_LABELS[item.module]}</span><span className="phase3e-pill">{item.verificationStatus}</span></div><h3>{item.title}</h3><p className="muted">{item.subtitle}</p><button onClick={()=>openItem(item)}>Open</button></article>)}</section>
   <section className="card"><div className="card-head"><h2>Source registry</h2><span className="muted">{SOURCE_RECORDS.length} investigated sources</span></div>{SOURCE_RECORDS.map(source=><article className="phase3e-card" key={source.id}><div className="phase3e-meta"><span className="phase3e-pill">{source.licenseStatus.replaceAll('_',' ')}</span><span className="phase3e-pill">{source.verificationStatus}</span></div><h3>{source.sourceName}</h3><p>{source.publisher}{source.edition?` · ${source.edition}`:''}</p><p className="muted">{sourceStatusLabel(source)}</p><p className="footnote">{source.notes}</p><a href={source.externalUrl} target="_blank" rel="noreferrer">Open source ↗</a></article>)}</section>
  </>:<LearningReader item={selected} state={state} commit={commit} onBack={()=>setSelected(null)} />}
 </div></div>
}

function LearningReader({item,state,commit,onBack}:{item:LearningItem;state:LearningState;commit:(state:LearningState)=>void;onBack:()=>void}){
 const track=state.tracks[item.module]; const bookmarked=track?.bookmarkedItemIds.includes(item.id)??false; const completed=track?.completedItemIds.includes(item.id)??false; const note=state.notes[item.id]??''; const textSize=track?.textSize??'default';
 return <section><header className="card-head"><div><button onClick={onBack}>← Back</button><p className="eyebrow">{MODULE_LABELS[item.module]}</p><h2>{item.title}</h2></div></header><div className="phase3e-meta"><span className="phase3e-pill">{item.verificationStatus}</span><span className="phase3e-pill">SOURCE CONTENT</span></div><p className={`phase3e-reader ${textSize}`}>{item.content||'Verified source content unavailable.'}</p><div className="row"><button onClick={()=>commit(toggleBookmark(state,item.module,item.id))}>{bookmarked?'Remove bookmark':'Bookmark'}</button><button onClick={()=>commit(completed?state:markCompleted(state,item.module,item.id))}>{completed?'Completed':'Mark complete'}</button><button onClick={()=>commit({...state,tracks:{...state.tracks,[item.module]:{...(state.tracks[item.module]??{currentItemId:null,completedItemIds:[],bookmarkedItemIds:[],lastReadAt:null,textSize:'default'}),textSize:textSize==='default'?'large':textSize==='large'?'xlarge':'default'}}})}>Text size</button><button disabled={!canShare(item)} onClick={()=>{if(canShare(item)&&navigator.share)navigator.share({title:item.title,text:`${item.title}\nSource: ${item.sourceName}\nReference: ${item.reference}`}).catch(()=>undefined)}}>Share</button></div><div className="card"><p className="footnote">Source: {item.sourceName} · {item.sourceVersion} · {item.edition}</p><p className="footnote">Reference: {item.reference}</p><p className="footnote">Review: {item.reviewStatus}</p><p className="footnote">Audio: {audioStatus(item)}</p></div><div className="card"><h3>USER NOTE</h3><textarea className="phase3e-note" value={note} onChange={e=>commit(setNote(state,item.id,e.target.value))} placeholder="Private note — not source content." aria-label="Private user note"/><p className="footnote">Stored locally on this device. Never presented as source content or a religious ruling.</p></div></section>
}
