import type {ZakatInputs,ZakatResult} from './zakat'
import type {FastRecord} from './fasting'
import {DEFAULT_RAMADAN_STATE,type JournalEntry,type RamadanDateState,type RamadanGoal} from './ramadan'
export type StoredZakat={id:string;savedAt:string;input:ZakatInputs;result:Pick<ZakatResult,'zakatableTotal'|'nisabValue'|'qualifies'|'estimatedZakat'>}
export type Phase3BState={version:1;zakatHistory:StoredZakat[];fasting:Record<string,FastRecord>;ramadan:{dateState:RamadanDateState;goals:RamadanGoal[];goalProgress:Record<string,number>;journal:Record<string,JournalEntry>}}
const KEY='noortools:phase3b:v1';const EMPTY:Phase3BState={version:1,zakatHistory:[],fasting:{},ramadan:{dateState:DEFAULT_RAMADAN_STATE,goals:[],goalProgress:{},journal:{}}};const clone=()=>structuredClone(EMPTY);const object=(v:unknown):v is Record<string,unknown>=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v);const str=(v:unknown):v is string=>typeof v==='string';const num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)
function migrate(raw:unknown):Phase3BState{if(!object(raw)||raw.version!==1)return clone();const z:StoredZakat[]=[];if(Array.isArray(raw.zakatHistory))for(const x of raw.zakatHistory){if(!object(x)||!str(x.id)||!str(x.savedAt)||!object(x.input)||!object(x.result))continue;const r=x.result;if(!num(r.zakatableTotal)||!num(r.nisabValue)||typeof r.qualifies!=='boolean'||!num(r.estimatedZakat))continue;z.push(x as unknown as StoredZakat)}
 const fasting:Record<string,FastRecord>={};if(object(raw.fasting))for(const [k,v] of Object.entries(raw.fasting)){if(!object(v)||!str(v.date)||!str(v.status)||k!==v.date||!['completed','missed','planned','pending'].includes(v.status))continue;fasting[k]={date:v.date,status:v.status as FastRecord['status'],note:str(v.note)?v.note.slice(0,1000):''}}
 const rr=object(raw.ramadan)&&object(raw.ramadan)?raw.ramadan:{};let dateState:RamadanDateState=DEFAULT_RAMADAN_STATE;if(object(rr.dateState)){const ds=rr.dateState;if((ds.source==='not_confirmed'||ds.source==='calculated_expected'||ds.source==='verified_authority'||ds.source==='custom')&&(ds.startDate===null||str(ds.startDate))&&str(ds.label))dateState={source:ds.source,startDate:ds.startDate,label:ds.label}}
 const goals:RamadanGoal[]=[];if(Array.isArray(rr.goals))for(const g of rr.goals){if(!object(g)||!str(g.id)||!str(g.label)||!num(g.target)||g.target<=0||!str(g.unit)||!str(g.createdAt))continue;goals.push({id:g.id,label:g.label.slice(0,120),target:g.target,unit:g.unit.slice(0,40),createdAt:g.createdAt})}const goalProgress:Record<string,number>={};if(object(rr.goalProgress))for(const [id,v] of Object.entries(rr.goalProgress))if(num(v)&&v>=0&&v<=1e12)goalProgress[id]=v
 const journal:Record<string,JournalEntry>={};if(object(rr.journal))for(const [id,v] of Object.entries(rr.journal))if(object(v)&&str(v.id)&&str(v.date)&&str(v.text)&&str(v.createdAt)&&str(v.updatedAt)&&Array.isArray(v.tags))journal[id]={id:v.id,date:v.date,text:v.text.slice(0,5000),mood:str(v.mood)?v.mood.slice(0,40):'',tags:v.tags.filter((t):t is string=>str(t)).slice(0,12),createdAt:v.createdAt,updatedAt:v.updatedAt}
 return {version:1,zakatHistory:z.slice(-100),fasting,ramadan:{dateState,goals:goals.slice(0,100),goalProgress,journal}}
}
export function loadPhase3BState():Phase3BState{try{const raw=localStorage.getItem(KEY);return raw?migrate(JSON.parse(raw)):clone()}catch{return clone()}}
export function savePhase3BState(state:Phase3BState){localStorage.setItem(KEY,JSON.stringify({...state,version:1}))}
export function resetPhase3BState(){localStorage.removeItem(KEY);return clone()}
export function saveZakat(state:Phase3BState,input:ZakatInputs,result:Pick<ZakatResult,'zakatableTotal'|'nisabValue'|'qualifies'|'estimatedZakat'>,now=new Date()):Phase3BState{const id=`zakat:${now.toISOString()}`;return {...state,zakatHistory:[...state.zakatHistory,{id,savedAt:now.toISOString(),input,result}].slice(-100)}}
export function deleteZakat(state:Phase3BState,id:string):Phase3BState{return {...state,zakatHistory:state.zakatHistory.filter(x=>x.id!==id)}}
export function clearZakat(state:Phase3BState):Phase3BState{return {...state,zakatHistory:[]}}
