export type RamadanSource='not_confirmed'|'calculated_expected'|'verified_authority'|'custom'
export type RamadanDateState={source:RamadanSource;startDate:string|null;label:string}
export type RamadanGoal={id:string;label:string;target:number;unit:string;createdAt:string}
export type JournalEntry={id:string;date:string;text:string;mood?:string;tags:string[];createdAt:string;updatedAt:string}
const DATE=/^\d{4}-\d{2}-\d{2}$/
export const DEFAULT_RAMADAN_STATE:RamadanDateState={source:'not_confirmed',startDate:null,label:'Ramadan date not confirmed'}
export function countdownToRamadan(state:RamadanDateState,now=new Date()){if((state.source!=='verified_authority'&&state.source!=='custom')||!state.startDate)return null;const target=new Date(`${state.startDate}T00:00:00Z`);const ms=target.getTime()-now.getTime();return {milliseconds:ms,days:Math.ceil(ms/86400000),started:ms<=0}}
export function validateRamadanStart(state:RamadanDateState){if(state.source==='not_confirmed'){if(state.startDate!==null)throw new Error('Unconfirmed Ramadan state cannot contain a start date.');return state}if(!state.startDate||!DATE.test(state.startDate)||Number.isNaN(new Date(`${state.startDate}T00:00:00Z`).getTime()))throw new Error('A valid Ramadan start date is required for this source state.');return {...state,label:state.source==='custom'?'Custom Ramadan start':'Verified authority Ramadan start'}}
export function createGoal(label:string,target:number,unit:string,now=new Date()):RamadanGoal{if(!label.trim()||!Number.isFinite(target)||target<=0||target>1e9||!unit.trim())throw new Error('Goal label, positive target and unit are required.');return {id:`ramadan-goal:${now.getTime()}:${Math.random().toString(36).slice(2,8)}`,label:label.trim().slice(0,120),target,unit:unit.trim().slice(0,40),createdAt:now.toISOString()}}
export function upsertJournal(entries:Record<string,JournalEntry>,date:string,text:string,mood='',tags:string[]=[],now=new Date()){if(!DATE.test(date)||Number.isNaN(new Date(`${date}T00:00:00Z`).getTime()))throw new Error('Journal date is invalid.');if(!text.trim())throw new Error('Journal text is required.');const id=`journal:${date}`;const previous=entries[id];return {...entries,[id]:{id,date,text:text.trim().slice(0,5000),mood:mood.trim().slice(0,40),tags:Array.from(new Set(tags.map(t=>t.trim().slice(0,40)).filter(Boolean))).slice(0,12),createdAt:previous?.createdAt??now.toISOString(),updatedAt:now.toISOString()}}}
export function removeJournal(entries:Record<string,JournalEntry>,id:string){const next={...entries};delete next[id];return next}
