export type SalahName = 'Fajr' | 'Dhuhr' | 'Asr' | 'Maghrib' | 'Isha'
export type SalahRecord = Partial<Record<SalahName, boolean>>
export type SalahState = Record<string, SalahRecord>
export type TasbihSession = { date: string; count: number; target: number; dhikr: string }
export type LocationState = { lat: number; lon: number; label: string; timeZone: string | null }
export type CalculationMethod = 'MWL' | 'ISNA' | 'Egypt' | 'Makkah' | 'Karachi' | 'Tehran' | 'Jafari'
export type HighLatitudeMethod = 'none' | 'angleBased' | 'oneSeventh' | 'middleOfNight'
export type AsrMethod = 'standard' | 'hanafi'
export type PrayerAdjustmentsState = Partial<Record<'Fajr' | 'Dhuhr' | 'Asr' | 'Maghrib' | 'Isha', number>>
export type PrayerSettingsState = { method: CalculationMethod; asrMethod: AsrMethod; hanafi: boolean; highLatitude: HighLatitudeMethod; adjustments: PrayerAdjustmentsState; timeFormat: '12h' | '24h' }
import { preserveCorruptStorage } from './storageRecovery'

export type AppState = { version: 3; location: LocationState | null; prayerSettings: PrayerSettingsState; salah: SalahState; tasbih: { count: number; target: number; dhikr: string; sessions: TasbihSession[]; total: number; haptic: boolean; sound: boolean } }
type ExportEnvelope = { schema: 'noortools.local-data'; version: number; data: unknown }
const KEY = 'noortools:v3'
const LEGACY_KEYS = ['noortools:v2', 'noortools:v1'] as const
const empty: AppState = { version: 3, location: null, prayerSettings: { method: 'MWL', asrMethod: 'standard', hanafi: false, highLatitude: 'none', adjustments: {}, timeFormat: '12h' }, salah: {}, tasbih: { count: 0, target: 33, dhikr: 'SubhanAllah', sessions: [], total: 0, haptic: true, sound: false } }
const cloneEmpty = () => structuredClone(empty)
const nonNegative = (value: unknown, fallback: number) => typeof value === 'number' && Number.isFinite(value) && value >= 0 ? value : fallback
const positive = (value: unknown, fallback: number) => typeof value === 'number' && Number.isFinite(value) && value > 0 ? value : fallback
function validLocation(value: unknown): LocationState | null { if (value === null) return null; if (!value || typeof value !== 'object' || Array.isArray(value)) return null; const v = value as Record<string, unknown>; const timeZone = typeof v.timeZone === 'string' && v.timeZone.trim() ? v.timeZone : null; return typeof v.label === 'string' && typeof v.lat === 'number' && Number.isFinite(v.lat) && Math.abs(v.lat) <= 90 && typeof v.lon === 'number' && Number.isFinite(v.lon) && Math.abs(v.lon) <= 180 ? { label: v.label.trim().slice(0, 120), lat: v.lat, lon: v.lon, timeZone } : null }
function validSalah(value: unknown): SalahState { if (!value || typeof value !== 'object' || Array.isArray(value)) return {}; const result: SalahState = {}; for (const [date, record] of Object.entries(value)) { if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !record || typeof record !== 'object' || Array.isArray(record)) continue; const cleaned: SalahRecord = {}; for (const name of ['Fajr', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'] as const) if ((record as Record<string, unknown>)[name] === true) cleaned[name] = true; if (Object.keys(cleaned).length) result[date] = cleaned } return result }
function validSessions(value: unknown): TasbihSession[] { if (!Array.isArray(value)) return []; return value.flatMap(s => { if (!s || typeof s !== 'object' || Array.isArray(s)) return []; const item = s as Record<string, unknown>; const date = typeof item.date === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(item.date) ? item.date : ''; const count = nonNegative(item.count, 0); const target = positive(item.target, 33); const dhikr = typeof item.dhikr === 'string' && item.dhikr.trim() ? item.dhikr.trim().slice(0, 160) : 'SubhanAllah'; return date && count > 0 ? [{ date, count, target, dhikr }] : [] }) }
function validAdjustments(value: unknown): PrayerAdjustmentsState { if (!value || typeof value !== 'object' || Array.isArray(value)) return {}; const result: PrayerAdjustmentsState = {}; for (const name of ['Fajr', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'] as const) { const raw = (value as Record<string, unknown>)[name]; if (typeof raw === 'number' && Number.isFinite(raw) && raw >= -120 && raw <= 120) result[name] = raw } return result }
function validPrayerSettings(value: unknown): PrayerSettingsState { if (!value || typeof value !== 'object' || Array.isArray(value)) return structuredClone(empty.prayerSettings); const p = value as Record<string, unknown>; const method = ['MWL', 'ISNA', 'Egypt', 'Makkah', 'Karachi', 'Tehran', 'Jafari'].includes(String(p.method)) ? p.method as CalculationMethod : 'MWL'; const asrMethod = p.asrMethod === 'hanafi' || p.hanafi === true ? 'hanafi' : 'standard'; const highLatitude = p.highLatitude === 'angleBased' || p.highLatitude === 'oneSeventh' || p.highLatitude === 'middleOfNight' ? p.highLatitude : 'none'; return { method, asrMethod, hanafi: asrMethod === 'hanafi', highLatitude, adjustments: validAdjustments(p.adjustments), timeFormat: p.timeFormat === '24h' ? '24h' : '12h' } }
function migrate(raw: unknown): AppState { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('Stored NoorTools data has an invalid structure.'); const parsed = raw as { version?: unknown; location?: unknown; prayerSettings?: unknown; salah?: unknown; tasbih?: unknown }; if (parsed.version !== 1 && parsed.version !== 2 && parsed.version !== 3 && parsed.version !== undefined) throw new Error('Stored NoorTools data uses an unsupported version.'); const t = parsed.tasbih && typeof parsed.tasbih === 'object' && !Array.isArray(parsed.tasbih) ? parsed.tasbih as Record<string, unknown> : {}; return { version: 3, location: validLocation(parsed.location), prayerSettings: validPrayerSettings(parsed.prayerSettings), salah: validSalah(parsed.salah), tasbih: { count: nonNegative(t.count, 0), target: positive(t.target, 33), dhikr: typeof t.dhikr === 'string' && t.dhikr.trim() ? t.dhikr.trim().slice(0, 160) : 'SubhanAllah', sessions: validSessions(t.sessions), total: nonNegative(t.total, 0), haptic: typeof t.haptic === 'boolean' ? t.haptic : true, sound: typeof t.sound === 'boolean' ? t.sound : false } } }
export function localDateKey(date = new Date(), timeZone?: string) { if (!timeZone) return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; const parts = new Intl.DateTimeFormat('en-CA', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(date); const values = Object.fromEntries(parts.filter(p => p.type !== 'literal').map(p => [p.type, p.value])) as Record<string, string>; return `${values.year}-${values.month}-${values.day}` }
export function loadState(): AppState {
  for (const key of [KEY, ...LEGACY_KEYS]) {
    let raw: string | null = null
    try { raw = localStorage.getItem(key) } catch { continue }
    if (!raw) continue
    try { return migrate(JSON.parse(raw)) }
    catch (error) {
      preserveCorruptStorage(key, raw, error instanceof Error ? error.message : 'Stored data could not be migrated safely.')
    }
  }
  return cloneEmpty()
}
export function saveState(state: AppState) { localStorage.setItem(KEY, JSON.stringify({ ...state, version: 3 })) }
export function resetState() { localStorage.removeItem(KEY); for (const key of LEGACY_KEYS) localStorage.removeItem(key); for (const key of [KEY, ...LEGACY_KEYS]) localStorage.removeItem(`${key}:recovery:v1`); return cloneEmpty() }
export function exportData(state: AppState): string { return JSON.stringify({ schema: 'noortools.local-data', version: 3, data: { location: state.location, prayerSettings: state.prayerSettings, salah: state.salah, tasbih: state.tasbih } } satisfies ExportEnvelope, null, 2) }
export function parseImportedData(text: string): AppState { if (typeof text !== 'string' || text.length > 2_000_000) throw new Error('Import file is too large or invalid.'); let parsed: unknown; try { parsed = JSON.parse(text) } catch { throw new Error('Import file is not valid JSON.') } if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('Import file must contain a NoorTools data object.'); const envelope = parsed as Partial<ExportEnvelope>; if (envelope.schema !== 'noortools.local-data') throw new Error('This file is not a NoorTools local-data export.'); if (typeof envelope.version !== 'number' || ![1, 2, 3].includes(envelope.version)) throw new Error('Unsupported NoorTools data version.'); if (!envelope.data || typeof envelope.data !== 'object' || Array.isArray(envelope.data)) throw new Error('NoorTools export data is missing.'); const source = envelope.data as Record<string, unknown>; if (!('location' in source) || !('salah' in source) || !('tasbih' in source)) throw new Error('NoorTools export is structurally incomplete.'); if (source.location !== null && validLocation(source.location) === null) throw new Error('Imported location data is invalid.'); if (source.salah === null || typeof source.salah !== 'object' || Array.isArray(source.salah)) throw new Error('Imported Salah data is invalid.'); if (source.tasbih === null || typeof source.tasbih !== 'object' || Array.isArray(source.tasbih)) throw new Error('Imported Tasbih data is invalid.'); return migrate({ ...source, version: envelope.version }) }
function dateNumber(key: string) { const [year, month, day] = key.split('-').map(Number); return Date.UTC(year, month - 1, day) / 86400000 }
function daysAgo(today: Date, key: string, timeZone?: string) { return dateNumber(localDateKey(today, timeZone)) - dateNumber(key) }
function shiftDateKey(key: string, days: number) { const [year, month, day] = key.split('-').map(Number); const d = new Date(Date.UTC(year, month - 1, day + days)); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}` }
export function salahStats(salah: SalahState, today = new Date(), timeZone?: string) { const todayKey = localDateKey(today, timeZone); const days = Object.entries(salah).filter(([, value]) => Object.values(value).some(Boolean)).map(([key, value]) => ({ key, completed: Object.values(value).filter(Boolean).length })); const todayCompleted = Object.values(salah[todayKey] ?? {}).filter(Boolean).length; const within = (limit: number) => days.filter(({ key }) => { const diff = daysAgo(today, key, timeZone); return diff >= 0 && diff < limit }).reduce((sum, day) => sum + day.completed, 0); let streak = 0; let key = todayKey; while (Object.values(salah[key] ?? {}).filter(Boolean).length === 5) { streak += 1; key = shiftDateKey(key, -1) } return { todayCompleted, last7: within(7), last30: within(30), streak } }
export function tasbihStats(sessions: TasbihSession[], today = new Date(), timeZone?: string) { const todayKey = localDateKey(today, timeZone); const within = (limit: number) => sessions.filter(session => { const diff = daysAgo(today, session.date, timeZone); return diff >= 0 && diff < limit }).reduce((sum, session) => sum + session.count, 0); const dates = new Set(sessions.map(session => session.date)); let streak = 0; let key = todayKey; while (dates.has(key)) { streak += 1; key = shiftDateKey(key, -1) } return { today: sessions.filter(s => s.date === todayKey).reduce((sum, s) => sum + s.count, 0), last7: within(7), last30: within(30), streak } }